// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebConsulting.Models;

public partial class Application
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [StringLength(255)]
    public string CompanyName { get; set; }

    [Required]
    [StringLength(255)]
    public string CompanyAddress { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    public bool IsDeleted { get; set; }

    [StringLength(200)]
    public string DeleteReason { get; set; }

    [StringLength(20)]
    public string DeletedBy { get; set; }

    [StringLength(50)]
    public string DeletedByUserId { get; set; }

    [InverseProperty("Application")]
    public virtual ICollection<ApplicationService> ApplicationServices { get; set; } = new List<ApplicationService>();

    [ForeignKey("UserId")]
    [InverseProperty("Applications")]
    public virtual User User { get; set; }
}