// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebConsulting.Models;

public partial class Service
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    [StringLength(50)]
    public string Price { get; set; }

    [StringLength(100)]
    public string Category { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();
}