// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebConsulting.Models;

public partial class Service
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [Required]
    public string Description { get; set; }

    public int? Price { get; set; }

    [StringLength(100)]
    public string Category { get; set; }

    public string FormattedPrice => Price.HasValue ? $"от {Price.Value:n0} р." : "Цена не указана";

    [InverseProperty("Service")]
    public virtual ICollection<ApplicationService> ApplicationServices { get; set; } = new List<ApplicationService>();
}